### EGEOFFREY ###
# docker build -f Dockerfile-standalone . -t egeoffrey/egeoffrey-gui_standalone:master-amd64
# docker push egeoffrey/egeoffrey-gui_standalone:master-amd64

### define base image
FROM egeoffrey/egeoffrey-gui:master-amd64

### configure the image
ENTRYPOINT []
CMD cp -f setup/nginx.conf /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;' -c /etc/nginx/nginx.conf
